CREATE TABLE IF NOT EXISTS "industries" (
  "id" serial PRIMARY KEY NOT NULL,
  "slug" text NOT NULL,
  "name" text NOT NULL,
  "short_label" text DEFAULT '' NOT NULL,
  "nav_title" text DEFAULT '' NOT NULL,
  "meta_description" text DEFAULT '' NOT NULL,
  "hero_eyebrow" text DEFAULT '' NOT NULL,
  "hero_title" text DEFAULT '' NOT NULL,
  "hero_subtitle" text DEFAULT '' NOT NULL,
  "pain_points" text DEFAULT '[]' NOT NULL,
  "regulations" text DEFAULT '[]' NOT NULL,
  "software_stacks" text DEFAULT '[]' NOT NULL,
  "what_we_do" text DEFAULT '[]' NOT NULL,
  "testimonial_quote" text DEFAULT '' NOT NULL,
  "testimonial_name" text DEFAULT '' NOT NULL,
  "testimonial_role" text DEFAULT '' NOT NULL,
  "testimonial_company" text DEFAULT '' NOT NULL,
  "case_study_hint" text DEFAULT '' NOT NULL,
  "related_services" text DEFAULT '[]' NOT NULL,
  "cta_label" text DEFAULT 'Book a consultation' NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "industries_slug_unique" UNIQUE("slug")
);
