import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import ssoRouter from "./sso";
import contactRouter from "./contact";
import quotesRouter from "./quotes";
import ticketsRouter from "./tickets";
import chatRouter from "./chat";
import cmsRouter from "./cms";
import partnersRouter from "./partners";
import openaiRouter from "./openai";
import documentsRouter from "./documents";
import tsdRouter from "./tsd";
import webhooksRouter from "./webhooks";
import zoomWebhookRouter from "./zoomWebhook";
import invoicesRouter from "./invoices";
import reportsRouter from "./reports";
import serviceAvailabilityRouter from "./service-availability.js";
import placesRouter from "./places.js";
import affiliateRouter from "./affiliate.js";
import impactRouter from "./impact.js";
import marketplaceRouter from "./marketplace.js";
import partnerProposalsRouter from "./partner-proposals.js";
import vivintRouter from "./vivint.js";
import pageContentRouter from "./page-content";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(ssoRouter);
router.use(contactRouter);
router.use(quotesRouter);
router.use(ticketsRouter);
router.use(chatRouter);
router.use(cmsRouter);
router.use(partnersRouter);
router.use(openaiRouter);
router.use(documentsRouter);
router.use(tsdRouter);
router.use(webhooksRouter);
router.use(zoomWebhookRouter);
router.use(invoicesRouter);
router.use(reportsRouter);
router.use(serviceAvailabilityRouter);
router.use(placesRouter);
router.use(affiliateRouter);
router.use(impactRouter);
router.use("/marketplace", marketplaceRouter);
router.use("/partner/proposals", partnerProposalsRouter);
router.use("/vivint", vivintRouter);
router.use(pageContentRouter);

export default router;
